// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtR2hvg8hX6x8oFiC6DyU2E1MafS0XIo',
    appId: '1:613593069663:web:ca240685fa90e528f843ea',
    messagingSenderId: '613593069663',
    projectId: 'maps-bf503',
    authDomain: 'maps-bf503.firebaseapp.com',
    storageBucket: 'maps-bf503.firebasestorage.app',
    measurementId: 'G-DM49N6H11Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTTUZVD-buMaK2xlp1ownigFoMfvQUfM',
    appId: '1:613593069663:android:ed289fd604f55d2df843ea',
    messagingSenderId: '613593069663',
    projectId: 'maps-bf503',
    storageBucket: 'maps-bf503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7S3TVpjzs2gCQwPb63cmyeFknWg5xxI',
    appId: '1:613593069663:ios:fbd0be304e2e6448f843ea',
    messagingSenderId: '613593069663',
    projectId: 'maps-bf503',
    storageBucket: 'maps-bf503.firebasestorage.app',
    iosBundleId: 'com.example.mapsAndThemeing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7S3TVpjzs2gCQwPb63cmyeFknWg5xxI',
    appId: '1:613593069663:ios:fbd0be304e2e6448f843ea',
    messagingSenderId: '613593069663',
    projectId: 'maps-bf503',
    storageBucket: 'maps-bf503.firebasestorage.app',
    iosBundleId: 'com.example.mapsAndThemeing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXtR2hvg8hX6x8oFiC6DyU2E1MafS0XIo',
    appId: '1:613593069663:web:3ee4d9a11382f3d8f843ea',
    messagingSenderId: '613593069663',
    projectId: 'maps-bf503',
    authDomain: 'maps-bf503.firebaseapp.com',
    storageBucket: 'maps-bf503.firebasestorage.app',
    measurementId: 'G-7CRHT2616S',
  );
}
